- type: replace
  path: /vm_types/name=default/cloud_properties/instance_type
  value: Basic_A1
- type: replace
  path: /vm_types/name=large/cloud_properties/instance_type
  value: Standard_D1_v2
- type: replace
  path: /networks/name=default/subnets/0/static?
  value: [10.0.16.20-10.0.16.50]
