---
# bosh interpolate concourse-haproxy.yml --vars-store ./creds-concourse.yml -v internal_ip=10.244.0.200 -v external_ip=concourse.example.com
# bosh deploy -d concourse concourse-haproxy.yml -v internal_ip=10.244.0.200 -v external_ip=concourse.example.com # CredHub
# bosh deploy -d concourse concourse-haproxy.yml --vars-store ./creds-concourse.yml -v internal_ip=10.244.0.200 -v external_ip=concourse.example.com

name: concourse

releases:
- name: concourse
  version: 3.3.4
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.3.4
  sha1: 17bdc7dbdc8d2b642f6796e1eb542fb9b2e962e2
- name: garden-runc
  version: 1.6.0
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.6.0
  sha1: 58fbc64aff303e6d76899441241dd5dacef50cb7
- name: concourse-bbr
  version: 0.3.0
  url: https://github.com/making/concourse-bbr-boshrelease/releases/download/0.3.0/concourse-bbr-0.3.0.tgz
  sha1: 1ef264e56c315836051c1c5c675c60427f9320e5

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
    static_ips: [((internal_ip))]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: &external_url https://((external_ip))
      basic_auth_username: admin
      basic_auth_password: ((ui_password))
      bind_port: 80
      postgresql_database: &atc_db atc
      # encryption_key: ((encryption_key))
      # old_encryption_key: ((old_encryption_key))
  - name: tsa
    release: concourse
    properties: {}
- name: db
  instances: 1
  vm_type: default
  persistent_disk_type: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        role: atc
        password: ((postgres_password))
  - name: db-backup
    release: concourse-bbr
- name: worker
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: atc_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((external_ip))
    alternative_names: [((external_ip))]
- name: postgres_password
  type: password
- name: ui_password
  type: password
- name: encryption_key
  type: password
  options:
    length: 16
- name: old_encryption_key
  type: password
  options:
    length: 16
