---
name: gitlab

releases:
- name: docker
  version: 30.1.3
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.1.3/docker-30.1.3.tgz
  sha1: bd6f68b9981453fbc72f50c15119f16663f27bad

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: gitlab
  azs: [z1]
  instances: 1
  persistent_disk_type: large
  vm_type: large
  stemcell: trusty
  networks:
  - name: default
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"
  - name: containers
    release: docker
    properties:
      containers:
      - name: gitlab
        image: "gitlab/gitlab-ce"
        privileged: true
        bind_ports:
        - "80:80"
        - "443:443"
        - "2222:22"
        volumes:
        - "/var/vcap/store/gitlab/config:/etc/gitlab"
        - "/var/vcap/store/gitlab/data:/var/opt/gitlab"
        - "/var/vcap/store/gitlab/logs:/var/log/gitlab"

variables:
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

