---
# bosh interpolate nexus.yml -v internal_ip=10.244.0.205
# bosh deploy -d nexus nexus.yml -v internal_ip=10.244.0.205

name: nexus

releases:
- name: nexus
  version: 0.3.2
  url: https://github.com/making/nexus-boshrelease/releases/download/0.3.2/nexus-0.3.2.tgz
  sha1: 0e2c2893c8cb12efd878cdbf3a07691567413be0

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: default
  persist_disk: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
    static_ips: [((internal_ip))]
  jobs:
  - name: nexus
    release: nexus
  - name: nexus-backup
    release: nexus

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

