releases:
- name: node-exporter
  version: 1.1.0
  url: https://github.com/cloudfoundry-community/node-exporter-boshrelease/releases/download/v1.1.0/node-exporter-1.1.0.tgz
  sha1: 88c8d7c150acc3b74520a47ad91165b3a40e032f
- name: syslog
  version: 11
  url: https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=11
  sha1: 332ac15609b220a3fdf5efad0e0aa069d8235788
addons:
- name: node_exporter
  jobs:
  - name: node_exporter
    release: node-exporter
- name: logs
  jobs:
  - name: syslog_forwarder
    release: syslog
    exclude:
    - reactive-syslog-server
    properties:
      syslog:
        address: 10.244.0.230
        transport: tcp
        port: 10514
        tls_enabled: false
