- type: replace
  path: /vm_types/name=default?/cloud_properties/instance_type
  value: Standard_B1s
- type: replace
  path: /vm_types/name=minimal?/cloud_properties/instance_type
  value: Standard_B1s
- type: replace
  path: /vm_types/name=small?/cloud_properties/instance_type
  value: Standard_B2s
- type: replace
  path: /vm_types/name=sharedcpu?/cloud_properties/instance_type
  value: Standard_B2s

